version: '3.7'
services:
  db:
    image: postgres:10.5
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=streamtest
    networks:
      db:
        aliases:
          - database
  augdiff-stream:
    image: osm_analytics:latest
    command: >
      /spark/bin/spark-submit
      --class osmesa.analytics.oneoffs.StreamingChangesetStatsUpdater
      /opt/osmesa-analytics.jar
      --augmented-diff-source ${AUGDIFF_SOURCE}
      --database-url postgresql://postgres:streamtest@database/postgres
      --start-sequence 1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
        window: 120s
    networks:
      - db
  changeset-stream:
    image: osm_analytics:latest
    command: >
      /spark/bin/spark-submit
      --class osmesa.analytics.oneoffs.StreamingChangesetMetadataUpdater
      /opt/osmesa-analytics.jar
      --start-sequence 1
      --database-url postgresql://postgres:streamtest@database/postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
        window: 120s
    networks:
      - db
networks:
  db:
